### ISSUE TITLE
> node --max-old-space-size=4096 ./node_modules/webpack-dev-server/bin/webpack-d ev-server --config config/webpack.dev.js 

### ISSUE THREAD

**Issue by razazaidisd** [dsebastien/angularjs-webpack-starter#190]
> node **--max-old-space-size=4096** ./node_modules/webpack-dev-server/bin/webpack-d ev-server --config **config/webpack.dev.js** --progress --profile --colors --watch - -display-error-details --display-cached --open "--hot" "--inline"

![image](https://cloud.githubusercontent.com/assets/6624130/15926651/4c18e970-2e4e-11e6-867f-9e65daea2bb2.png)

**Comment by SuperITMan** [comment]
Think to upgrade npm to the last version :)

**Comment by dsebastien** [comment]
Closing as there hasn't been any activity. Please reopen with more details if you still have the issue with the current master branch
